apiVersion: v1
kind: Service
metadata:
  name: simple-attendance-tracker-service
spec:
  type: LoadBalancer
  selector:
    app: simple-attendance-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
